---
- name: Copy-files example
  hosts: java_app
  become: true

  vars:
    user: 'Project Future 6 Devops Team 3'

  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /ansible_test_file.conf
    state: touch
    mode: u=rw,g=r,o=r
