- name: Deploy Java App & MySQL
  hosts: java_app_{{ branch_name }}
  become: true
  gather_facts: 'no'

  vars:
    branch_name: '{{ branch }}'
    build_number: '{{ build_nr }}'
    docker_volume: mysql_data
    docker_network: mysql_java_net
    db_name: mysql
    java_app_name: java_app_{{ branch_name }}

  tasks:
    - name: Create a docker network
      docker_network:
        name: '{{ docker_network }}'

    - name: Launch MySQL container
      docker_container:
        name: '{{ db_name }}'
        image: 'mysql:8'
        volumes:
          - '{{ docker_volume }}:/var/lib/mysql:rw'
        restart: true
        networks:
          - name: '{{ docker_network }}'
        env:
          MYSQL_ROOT_PASSWORD: root

    - name: Launch {{ branch_name }} Java App container
      docker_container:
        name: '{{ java_app_name }}'
        image: 'pavlidin/java-app:{{ branch_name }}build{{ build_number }}'
        restart: true
        networks:
          - name: '{{ docker_network }}'
        ports:
          - '80:8080'
