---
- name: Copy-files example
  hosts: java_app
  become: true

  vars:
    user: 'Project Future 6 Devops Team 3'

  tasks:
    - name: Deploy app in dev
      ping:
      # when: ansible_nodename == "java-app-dev-\*"

    - name: Create a data container
      docker_container:
        name: mydata
        image: busybox

    # - name: Deploy app in prod
    #   ping:
    #         when: ansible_nodename == "java-app-prod-\*"

    #test123
